### ISSUE TITLE
Eagerly-initialized variant?

### ISSUE THREAD

**Issue by alex** [Voultapher/self_cell#1]
This crate is wonderful, thank you! I've got a use case that'd benefit from a variant that's eagerly initialized, instead of lazily.

The reason is that my code for generating the dependant needs another parameter, in addition to owner. This means that `From::from`, which can be called anywhere doesn't work. Instead I'd benefit from an API that let's you do:

```rust
AstCell::new(body, |body| blah blah)
```

this way the closure could close over the other paramater.

Does this seem reasonable?

**Comment by zbraniecki** [comment]
This is also needed for fallible constructor scenario

**Comment by Voultapher** [comment]
Constructing with a closure is certainly a nicer API and its the way it used to be, but during review people found various ways of 'smuggling in wrong lifetimes', which made the interface unsound, for example https://users.rust-lang.org/t/experimental-safe-to-use-proc-macro-free-self-referential-structs-in-stable-rust/52775/2?u=voultapher. Several other things have changed since then, and SkiFire13 suggested to go back to the closure design https://users.rust-lang.org/t/experimental-safe-to-use-proc-macro-free-self-referential-structs-in-stable-rust/52775/27?u=voultapher. Maybe I'm being too cautious here, but for now its a risk I don't want to take. I want to get a solid safe-to-use base. Let's do potentially risky ergonomics extensions at a later point in time.

Regarding the fallible constructor scenario, unless I misunderstand what you mean, the dependent type can be `Result`, of course you'll have to have error checking on every subsequent access which isn't ideal, but functional for now.

Regarding eager initialization, I'm sure it can be supported, but not quite sure what a good API for it would be like. Given there are open soundness bugs, I will prioritize those first and come back to this issue after.

**Comment by Voultapher** [comment]
A further thought

> The reason is that my code for generating the dependant needs another parameter,

If your dependent depends even transitively on two values, then those are the owner. Wrap them in a newtype and this API works safely, because one of them can't accidentally life too short etc.

**Comment by Voultapher** [comment]
This gets addressed by #7. I've switched the default to eager initialization. Lazy initialization is now in the hands of users, although I'm providing an example that shows how it can be done.

**Comment by Voultapher** [comment]
@alex v.0.7 was released which completely drops the eager part, please let me know if this addresses this issue. In addition the `from_fn` constructor type should offer you a way to pass in more state safely as long as you don't return references to it.

**Comment by Voultapher** [comment]
Since I have not heard back from you @alex I'm assuming this is fixed.
