### ISSUE TITLE
Is it possible to use generic types inside self_cell?

### ISSUE THREAD

**Issue by mrcz** [Voultapher/self_cell#44]
When I try to use a generic type inside self_cell! I get the error: "no rules expected the token 'T'"

```rust
self_cell!(
    struct Node<T> {
       // ...
    }
);
```

Is this not supported or am I doing it wrong?

**Comment by Voultapher** [comment]
Currently it's not possible to use generic parameters on generated structs.

**Comment by Voultapher** [comment]
This feature is not planned for the foreseeable future, so I will close this issue.

**Comment by hniksic** [comment]
@Voultapher I don't want to beat a dead horse, but I'm curious as to why this feature is not planned. Is it due to soundness issues, or something technical with declarative macros? Or is the feature not considered useful enough to warrant complications?

After `MutBorrow` landed I hoped to get rid of ouroboros in our code base (due to the amount of unnecessary API it generates, and it being a proc macro). But I soon discovered that some of our usages are actually dependent on generics, and that self-cell doesn't support them - which is how I stumbled upon this issue.

**Comment by Voultapher** [comment]
@steffahn in the past you helped come up with this part of the code https://github.com/Voultapher/self_cell/blob/4bd08b6215428246e1f26f9d13c22bf13ae4358d/src/lib.rs#L606-L622, my questions are:

- Assuming only a single optional owner lifetime is allowed, would allowing
  generic parameters in the owner mess with existing trait bounds? Given that
  most of this happens via `JoinedCell` which is a generic type I don't see how
  it could, other than in the top-level macro generated code.
- Assuming only a single optional owner lifetime is allowed, would allowing
  generic parameters in the owner mess with the variance requirements?
- What about trait requirements on generic parameters - are they even useful,
  the only use I can think of would be other derive macros that leverage them -
  do they add further complications?
- Would allowing multiple owner lifetimes be a problem?
- Is owner only genericity even that useful?

**Comment by hniksic** [comment]
In my use case I don't need generics over the dependent, though it's hard to tell how typical that is. My concrete use case is - you'd never guess it - `ZipArchive`. Currently I have:

<details>
<summary>Click to expand code</summary>

```rust
/// Utility that reads all files in zip file concatenated using the `Read` interface.
pub struct ZipReader<R: Read + Seek + 'static>(Option<ZipReaderImpl<R>>);

#[ouroboros::self_referencing]
struct ZipReaderImpl<R: Read + Seek + 'static> {
    archive: ZipArchive<R>,
    #[borrows(mut archive)]
    #[not_covariant]
    current_file: ZipFile<'this>,
    current_index: usize,
}

impl<R: Read + Seek> ZipReader<R> {
    /// Create new `ZipReader` from given io `Read`, e.g. a zip `File`.
    pub fn new(reader: R) -> ZipResult<Self> {
        let archive = ZipArchive::new(reader)?;
        let mut new = Self(None);
        new.open_member(archive, 0)?;
        Ok(new)
    }

    fn next_file(&mut self) -> ZipResult<()> {
        let inner = self.0.take().unwrap().into_heads();
        self.open_member(inner.archive, inner.current_index + 1)
    }

    fn open_member(&mut self, archive: ZipArchive<R>, current_index: usize) -> ZipResult<()> {
        if current_index >= archive.len() {
            return Ok(());
        }
        let zip_reader_impl = ZipReaderImplTryBuilder {
            archive,
            current_file_builder: |archive| archive.by_index(current_index),
            current_index,
        }
        .try_build()?;
        *self = ZipReader(Some(zip_reader_impl));
        Ok(())
    }
}

impl<R: Read + Seek> Read for ZipReader<R> {
    fn read(&mut self, buf: &mut [u8]) -> Result<usize> {
        loop {
            let Some(inner) = self.0.as_mut() else {
                return Ok(0);
            };
            let to_return =
                inner.with_current_file_mut(|current_file| match current_file.read(buf) {
                    Err(err) => Some(Err(err)),
                    Ok(0) => {
                        // advance to next file and repeat...
                        None
                    }
                    Ok(n) => Some(Ok(n)),
                });
            if let Some(to_return) = to_return {
                return to_return;
            }
            self.next_file()?;
        }
    }
}
```
</details>

This is not the only self-referential usage in the workspace, but all others can use `self-cell`. I wouldn't like to use *two* self-referential crates, though, which is why I wanted to check how (un)likely is the support for generic owners.

**Comment by Voultapher** [comment]
> you'd never guess it - ZipArchive

Maybe I should pitch the zip crate people on the idea that they add a feature for a utility type that implements something similar, given how many times I have been contacted over this use-case now.
